lang: en-UK
url: https://phpwebdevelope.github.io
baseurl: /agency-jekyll-theme/
google_analytics: UA-110136381-1 
plugins:
  - jekyll-sitemap

# Site settings
title: House Of Fennel 
email: info@houseoffennel.com
description: "Jamaican Fashion House for womenswear - Indigenous Jamaican Creativity."


# Team names, titles and social links
people:
- name: M. M. Fennel
  pic: 1
  position: Creative Director
  social:
    - title: twitter
      url: https://www.twitter.com/houseoffennel
    - title: facebook
      url:  https://www.facebook.com/houseoffennel
    - title: instagram
      url: https://www.instagram.com/houseoffennel

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/houseoffennel
  - title: facebook
    url: https://www.facebook.com/houseoffennel
  - title: instagram
    url: https://www.instagram.com/houseoffennel
  - title: google plus 
    url: https://plus.google.com/112332268275126848746

# Postal address (add as many lines as necessary)
address:
  - line: Jamaica
  - line: West Indies

# Build settings
markdown: kramdown
permalink: pretty

